Config update
Polymer/tools-common pull request #10
Opened 2016-10-27 19:37 UTC by justinfagnani

2016-10-27 19:45 UTC, rictic requested changes

2016-10-27 19:45 UTC, rictic commented on tsconfig.json
> +  "exclude": [
This isn't strictly speaking necessary, as it's not in the include section. IMO, drop.

2016-10-27 19:45 UTC, rictic commented on package.template.json
> +    "clang-format": "=1.0.45",
Most of these deps should instead just be a dep on tools-common yeah?

2016-10-27 23:59 UTC, justinfagnani commented on tsconfig.json
> +  "exclude": [
Done

2016-10-28 00:04 UTC, justinfagnani commented on package.template.json
> +    "clang-format": "=1.0.45",
Done

2016-10-28 00:06 UTC, justinfagnani commented
PTAL

2016-10-28 00:07 UTC, rictic approved these changes

2016-10-28 00:11 UTC, merged